### ISSUE TITLE
Prepare a task to update an extension using the latest dev tools' features

### ISSUE THREAD

**Issue by blocknotes** [solidusio-contrib/solidus_extension_dev_tools#34]
We could create a task like `rails:update` for Rails to update an existing extension

**Comment by blocknotes** [comment]
After an initial check, if we run the create extension command on an existing extension it updates already the files from the template.

**Comment by aldesantis** [comment]
Yeah, I think the generator is enough. @elia what do you think?

**Comment by elia** [comment]
@aldesantis as long as the generator asks the user if they want to replace the file and offers a diff I'm fine with it 👍
